name: agrimate

description: A new Flutter project.

publish_to: "none"  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.11
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  intl: ^0.20.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.13.6
  image_picker: ^1.1.0
  http: ^1.1.2
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  flutter_dotenv: ^5.1.0
  weather_icons: ^3.0.0
  fl_chart: ^0.65.0
  slide_to_act: ^2.0.1
  getwidget: ^6.0.0
  url_launcher: ^6.2.4
  lottie: ^2.7.0
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/images/splash_logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          weight: 400
