name: agrimate

description: A new Flutter project.

publish_to: "none"  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  cupertino_icons: ^1.0.8

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.17.3
  image_picker: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
