// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiXrZFGqNwFZ0512eMsW-V-Hu8Ihop_Jg',
    appId: '1:622385962837:web:0aa1e4eff298ea522b19dc',
    messagingSenderId: '622385962837',
    projectId: 'agrimate-ab312',
    authDomain: 'agrimate-ab312.firebaseapp.com',
    storageBucket: 'agrimate-ab312.firebasestorage.app',
    measurementId: 'G-4R45NCB0GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzVATm7WSS7-3M3PLLB3IzoCnOAcvK9ig',
    appId: '1:622385962837:android:b88d60575a97601c2b19dc',
    messagingSenderId: '622385962837',
    projectId: 'agrimate-ab312',
    storageBucket: 'agrimate-ab312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJbnK3Ow9d7dnt6tKnO5wRC9b8_C7ZJA',
    appId: '1:622385962837:ios:ac5d6dc2767bc4182b19dc',
    messagingSenderId: '622385962837',
    projectId: 'agrimate-ab312',
    storageBucket: 'agrimate-ab312.firebasestorage.app',
    iosBundleId: 'com.example.agrimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJbnK3Ow9d7dnt6tKnO5wRC9b8_C7ZJA',
    appId: '1:622385962837:ios:ac5d6dc2767bc4182b19dc',
    messagingSenderId: '622385962837',
    projectId: 'agrimate-ab312',
    storageBucket: 'agrimate-ab312.firebasestorage.app',
    iosBundleId: 'com.example.agrimate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiXrZFGqNwFZ0512eMsW-V-Hu8Ihop_Jg',
    appId: '1:622385962837:web:7727548e2288a4f12b19dc',
    messagingSenderId: '622385962837',
    projectId: 'agrimate-ab312',
    authDomain: 'agrimate-ab312.firebaseapp.com',
    storageBucket: 'agrimate-ab312.firebasestorage.app',
    measurementId: 'G-VR6YMSR3EW',
  );
}
